#ifndef __EVENT_IDL__
#define __EVENT_IDL__

#include "CosEventComm.idl"
module Event
{
  //Estructura de los eventos  
  struct TIEMPO
  {
     //Tiempo en segundos
     unsigned long  	tv_sec;
     //Tiempo en milisegundos
     long   		tv_usec;
     //Identificador del evento
     long		id;
  };

  interface Server : CosEventComm::PushSupplier {
    oneway void enviar(in any dato);
    //void enviar(in any dato);
  };

};
#endif
